### ISSUE TITLE
Stuck in "Uploading and pre-processing, please wait" page

### ISSUE THREAD

**Issue by Dahlia7** [baidu/Curve#75]
Hey, while uploading CSV the localhost:/8080 web is stuck as picture below:

<img width="590" alt="loading" src="https://user-images.githubusercontent.com/8780698/70406392-856c7a80-1a7b-11ea-8a26-adfde2d2b5be.png">

My data is like

timestamp | value
1534521600 | 0.00
1534608000 | 0.00
1534694400 | 0.00
1534780800 | 1048.20
1534867200 | 0.00
1534953600 | 747.40
1535040000 | 14606.00
1535126400 | 7219.20
1535212800 | 150.40
1535299200 | 5228.00
1535385600 | 2450.40
1535472000 | 1101.40
1535558400 | 3808.60

**Comment by Dahlia7** [comment]
<img width="1434" alt="error" src="https://user-images.githubusercontent.com/8780698/70407568-ce263280-1a7f-11ea-9eb6-1d49331079e1.png">

**Comment by Dahlia7** [comment]
==> api/log/curve.log <==
ERROR: 2019-12-09 12:35:33.130071: line:189 * zero-size array to reduction operation minimum which has no identity

==> api/log/uwsgi.log <==
ERROR: 2019-12-09 12:35:33.130169: line:189 * zero-size array to reduction operation minimum which has no identity
[2019-12-09 12:35:33,130] ERROR in app: Exception on /v1/data/test_2 [POST]
Traceback (most recent call last):
  File "../venv/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "../venv/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "../venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "../venv/lib/python2.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "../venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/xili/Documents/python_workspace/Outlier_Label/Curve/api/curve/v1/validators.py", line 115, in wrapper
    resp = view(*args, **kwargs)
  File "/Users/xili/Documents/python_workspace/Outlier_Label/Curve/api/curve/v1/validators.py", line 106, in wrapper
    return view(*args, **kwargs)
  File "/Users/xili/Documents/python_workspace/Outlier_Label/Curve/api/curve/v1/api/data_dataName.py", line 109, in post
    _, (axis_min, axis_max) = plugin('y_axis', data_raw_list)  # cal y_axis for data
TypeError: 'NoneType' object is not iterable

==> api/log/curve.log <==
ERROR: 2019-12-09 12:35:33.133433: line:1891 * Exception on /v1/data/test_2 [POST]
Traceback (most recent call last):
  File "../venv/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "../venv/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "../venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "../venv/lib/python2.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "../venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/xili/Documents/python_workspace/Outlier_Label/Curve/api/curve/v1/validators.py", line 115, in wrapper
    resp = view(*args, **kwargs)
  File "/Users/xili/Documents/python_workspace/Outlier_Label/Curve/api/curve/v1/validators.py", line 106, in wrapper
    return view(*args, **kwargs)
  File "/Users/xili/Documents/python_workspace/Outlier_Label/Curve/api/curve/v1/api/data_dataName.py", line 109, in post
    _, (axis_min, axis_max) = plugin('y_axis', data_raw_list)  # cal y_axis for data
TypeError: 'NoneType' object is not iterable

==> api/log/uwsgi.log <==
ERROR: 2019-12-09 12:35:33.133540: line:1891 * Exception on /v1/data/test_2 [POST]
Traceback (most recent call last):
  File "../venv/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "../venv/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "../venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "../venv/lib/python2.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "../venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/xili/Documents/python_workspace/Outlier_Label/Curve/api/curve/v1/validators.py", line 115, in wrapper
    resp = view(*args, **kwargs)
  File "/Users/xili/Documents/python_workspace/Outlier_Label/Curve/api/curve/v1/validators.py", line 106, in wrapper
    return view(*args, **kwargs)
  File "/Users/xili/Documents/python_workspace/Outlier_Label/Curve/api/curve/v1/api/data_dataName.py", line 109, in post
    _, (axis_min, axis_max) = plugin('y_axis', data_raw_list)  # cal y_axis for data
TypeError: 'NoneType' object is not iterable
[pid: 39394|app: 0|req: 5/8] 127.0.0.1 () {52 vars in 1150 bytes} [Mon Dec  9 12:35:33 2019] POST /v1/data/test_2 => generated 37 bytes in 36 msecs (HTTP/1.1 500) 4 headers in 156 bytes (2 switches on core 1)

**Comment by songdo** [comment]
i got it
this tool only support hourly data

**Comment by david-waterworth** [comment]
There's a log file in /api/log/curve.log

For me the error message implies a python 2.7 / python 3.x issue - it's using string operations on a byte array. I suspect in order to get this working properly you need to create a venv with the correct package versions (i.e. looking at api/requirements.txt the minimum required versions are quite old and installing the latest probably causes issues)
