### ISSUE TITLE
安装过程中报错

### ISSUE THREAD

**Issue by wuxie2015** [baidu/Curve#88]
![image](https://user-images.githubusercontent.com/10534495/85217463-065de480-b3c4-11ea-96f2-06935e02c4b0.png)
在an zhuang guo ch安装过程中，报错
Traceback (most recent call last):
  File "/Users/zhanglin/Documents/tools/Curve_bak/Curve/venv/bin/swagger_py_codegen", line 5, in <module>
    from swagger_py_codegen import generate
  File "/Users/zhanglin/Documents/tools/Curve_bak/Curve/venv/lib/python2.7/site-packages/swagger_py_codegen/__init__.py", line 4, in <module>
    from .command import generate
  File "/Users/zhanglin/Documents/tools/Curve_bak/Curve/venv/lib/python2.7/site-packages/swagger_py_codegen/command.py", line 15, in <module>
    from .flask import FlaskGenerator
  File "/Users/zhanglin/Documents/tools/Curve_bak/Curve/venv/lib/python2.7/site-packages/swagger_py_codegen/flask.py", line 6, in <module>
    from .jsonschema import Schema, SchemaGenerator, build_default
  File "/Users/zhanglin/Documents/tools/Curve_bak/Curve/venv/lib/python2.7/site-packages/swagger_py_codegen/jsonschema.py", line 6, in <module>
    from .parser import schema_var_name
  File "/Users/zhanglin/Documents/tools/Curve_bak/Curve/venv/lib/python2.7/site-packages/swagger_py_codegen/parser.py", line 5, in <module>
    import dpath.util
  File "/Users/zhanglin/Documents/tools/Curve_bak/Curve/venv/lib/python2.7/site-packages/dpath/util.py", line 1, in <module>
    from collections.abc import MutableMapping
ImportError: No module named abc
但是colleciton.abc不是python3才支持的吗？

**Comment by minorcong** [comment]
也许应该调整下 swagger_py_codegen 的版本？

**Comment by brianhill11** [comment]
I had same issue... as a hacky fix I changed the import statement in `Curve/venv/lib/python2.7/site-packages/dpath/util.py`
from
```
from collections.abc import MutableMapping
from collections.abc import MutableSequence
```
to
```
try:
    from collections.abc import MutableMapping
    from collections.abc import MutableSequence
except ImportError:
    from collections import MutableMapping
    from collections import MutableSequence
```
and it seems to work.

**Comment by AlumiK** [comment]
> 也许应该调整下 swagger_py_codegen 的版本？

I've submitted a pull request, adding `dpath==1.5.0` as an explicit requirement.
